taxon_ids:
  target: 3435 #example target sequence
  base: 3702    #example base sequence

#below are example query sequences, should begin with a >, then name, followed with the amino acid fasta sequence in the next lane.
query_contents: |
  >sp|Q9LQT8.1|GAI_ARATH RecName: Full=DELLA protein GAI; AltName: Full=GRAS family protein 3; Short=AtGRAS-3; AltName: Full=Gibberellic acid-insensitive mutant protein; AltName: Full=Restoration of growth on ammonia protein 2
  MKRDHHHHHHQDKKTMMMNEEDDGNGMDELLAVLGYKVRSSEMADVAQKLEQLEVMMSNVQEDDLSQLAT
  ETVHYNPAELYTWLDSMLTDLNPPSSNAEYDLKAIPGDAILNQFAIDSASSSNQGGGGDTYTTNKRLKCS
  NGVVETTTATAESTRHVVLVDSQENGVRLVHALLACAEAVQKENLTVAEALVKQIGFLAVSQIGAMRKVA
  TYFAEALARRIYRLSPSQSPIDHSLSDTLQMHFYETCPYLKFAHFTANQAILEAFQGKKRVHVIDFSMSQ
  GLQWPALMQALALRPGGPPVFRLTGIGPPAPDNFDYLHEVGCKLAHLAEAIHVEFEYRGFVANTLADLDA
  SMLELRPSEIESVAVNSVFELHKLLGRPGAIDKVLGVVNQIKPEIFTVVEQESNHNSPIFLDRFTESLHY
  YSTLFDSLEGVPSGQDKVMSEVYLGKQICNVVACDGPDRVERHETLSQWRNRFGSAGFAAAHIGSNAFKQ
  ASMLLALFNGGEGYRVEESDGCLMLGWHTRPLIATSAWKLSTN
  >sp|Q9SLH3.1|RGA_ARATH RecName: Full=DELLA protein RGA; AltName: Full=GAI-related sequence; AltName: Full=GRAS family protein 10; Short=AtGRAS-10; AltName: Full=Repressor on the ga1-3 mutant; AltName: Full=Restoration of growth on ammonia protein 1
  MKRDHHQFQGRLSNHGTSSSSSSISKDKMMMVKKEEDGGGNMDDELLAVLGYKVRSSEMAEVALKLEQLE
  TMMSNVQEDGLSHLATDTVHYNPSELYSWLDNMLSELNPPPLPASSNGLDPVLPSPEICGFPASDYDLKV
  IPGNAIYQFPAIDSSSSSNNQNKRLKSCSSPDSMVTSTSTGTQIGGVIGTTVTTTTTTTTAAGESTRSVI
  LVDSQENGVRLVHALMACAEAIQQNNLTLAEALVKQIGCLAVSQAGAMRKVATYFAEALARRIYRLSPPQ
  NQIDHCLSDTLQMHFYETCPYLKFAHFTANQAILEAFEGKKRVHVIDFSMNQGLQWPALMQALALREGGP
  PTFRLTGIGPPAPDNSDHLHEVGCKLAQLAEAIHVEFEYRGFVANSLADLDASMLELRPSDTEAVAVNSV
  FELHKLLGRPGGIEKVLGVVKQIKPVIFTVVEQESNHNGPVFLDRFTESLHYYSTLFDSLEGVPNSQDKV
  MSEVYLGKQICNLVACEGPDRVERHETLSQWGNRFGSSGLAPAHLGSNAFKQASMLLSVFNSGQGYRVEE
  SNGCLMLGWHTRPLITTSAWKLSTAAY 
#
output_domains: "output/hmmer/domains/*.fasta"
filtered_pairs: "output/mcscanx/target_base.filtered_pairs.tsv"
setup_marker: "output/.setup_done"
secondary_query: "output/query.fasta"
base_blast: "output/blast/base_blastp.tsv"
target_blast: "output/blast/target_blastp.tsv"
hmmer_scan: "output/hmmer/hmmer_scan.txt"
hmmer_done: "output/hmmer/domains/.done"
sort_marker: "output/domain_sorted/query_hmmer/domains/.done"
sort_text: "output/domain_sorted/query_hmmer/hmmer_scan.txt"
unique_pairs: "output/blast/unique_pairs_no_dup.tsv"
meme_xml: "output/domain_sorted/meme_results/{domain}/meme.xml"
msa_aligned: "output/domain_sorted/msa/{domain}.aligned.fasta"
tree: "output/domain_sorted/tree/{domain}/{domain}.treefile"
mrna: "output/domain_sorted/mrna/{domain}/mrna.fasta"
first_property: "output/domain_sorted/properties/{domain}_pi_mw.tsv"
gmap_annotation: "output/domain_sorted/gmap/{domain}.gff3"
primers: "output/domain_sorted/primers/{domain}/{ptype}.txt"
annotations: "output/domain_sorted/annotations_by_domain/{domain}.gff"
select_genes: "output/domain_sorted/selected_genes/{domain}.txt"
promoters: "output/domain_sorted/promoters/{domain}_promoters.fasta"
promoter_meme: "output/domain_sorted/promoters/meme_results/{domain}/meme.html"
primersearch_txt: "output/domain_sorted/primers/{domain}/{ptype}/primersearch.txt"
primersearch_sim: "output/domain_sorted/primers/{domain}/{ptype}/_primersim.txt"
crispr: "output/domain_sorted/crispr/{domain}/scored.tsv"
pairs_to_run: "output/mcscanx/pairs_to_run.txt"
pair_cds: "output/pairs_calculations/cds/{pair}.fasta"
cds_align: "output/pairs_calculations/cds_aligned/{pair}.codon.fasta"
ka/ks: "output/pairs_calculations/kaks/{pair}.kaks.txt"
chromosome_map: "output/domain_sorted/chromosal_map/{domain}/chromosomal_map.png"
gene_structure: "output/domain_sorted/gene_structures/{domain}/gene_structures"
extra_properties: "output/domain_sorted/extra_properties/{domain}_physicochemical.csv"
true_query: "output/true_query.fasta"
target_proteome: "data/proteome/target/proteins.faa"
target_prot_prefix: "data/proteome/target"
target_tmp: "output/blast/tmp_target.tsv"
base_proteome: "data/proteome/base/proteins.faa"
base_prot_prefix: "data/proteome/base"
hit_ids: "output/hmmer/hit_ids.txt"
hit_seqs: "output/hmmer/hit_sequences.fasta"
pfam: "preset/pfam/Pfam-A.hmm"
domain_tbl: "output/domain_sorted/query_hmmer/domtblout.txt"
hmmer_hits: "output/domain_sorted/query_hmmer/combined_hits_query.fasta"
hmmer_skip: "output/domain_sorted/query_hmmer/SKIPPED"
combo_hits: "output/hmmer/combined_hits_query.fasta"
domain_fasta: "output/hmmer/domains/{domain}.fasta"
tree_skip: "output/domain_sorted/tree/{domain}/SKIPPED"
tree_log: "output/domain_sorted/tree/{domain}/{domain}.iqtree.log"
target_mrna: "data/genome/target/mrna.fasta"
target_annotation: "data/genome/target/annotation.db"
target_gmap: "data/gmap_db/target"
target_genome: "data/genome/target/genome.fna"
promoter_xml: "output/domain_sorted/promoters/meme_results/{domain}/meme.xml"
promoter_skip: "output/domain_sorted/promoters/meme_results/{domain}/SKIPPED"
mcscanx_wgd_pairs: "data/mcscanx/target_base.wgd_pairs.tsv"
conservation_stats: "output/mcscanx/conservation_stats.txt"
base_cds: "data/genome/base/cds.fasta"
target_cds: "data/genome/target/cds.fasta"
pair_cds_fasta: "output/pairs_calculations/cds_aligned/{pair}.prot.fasta"
cds_aligned_fasta: "output/pairs_calculations/cds_aligned/{pair}.prot.aln.fasta"
axt_convert: "output/pairs_calculations/kaks_input/{pair}.axt"
flash_fry_index: "data/flashfry_index/genome"
header: "data/flashfry_index/genome.header"
gRNA_discovery: "output/domain_sorted/crispr/{domain}/discovery.output"
target_gff: "data/genome/target/annotation.gff3"
target_fai: "data/genome/target/genome.fna.fai"

genome_group: "data/genome/{group}/genome.fna"
proteome_group: "data/proteome/{group}/proteins.faa"
annotation_group: "data/genome/{group}/annotation.gff3"
mrna_group: "data/genome/{group}/mrna.fasta"
filtered_group: "data/genome/{group}/annotation.filtered.gff3"
bed_group: "data/genome/{group}/genes.bed"
annotation_db_group: "data/genome/{group}/annotation.db"
protein_db_group: "data/proteome/{group}/proteins_db.done"
gmap_marker: "data/gmap_db/target/db.done"
group_pairs: "data/mcscanx/{genome}.wgd_pairs.tsv"
combo_gff: "data/mcscanx/target_base.gff"
genome_fna_fai: "data/genome/target/genome.fna.fai"
filtered_target: "data/genome/target/annotation.filtered.gff3"
base_genome: "data/genome/base/genome.fna"
filtered_based: "data/genome/base/annotation.filtered.gff3"
scan_combo: "data/mcscanx/{group}.gff"
filtered_target_gff: "data/mcscanx/target.gff"
filtered_base_gff: "data/mcscanx/base.gff"
group_filtered_gff: "data/mcscanx/{genome}.gff"
group_blase: "data/mcscanx/{genome}.blast"
group_collin: "data/mcscanx/{genome}.collinearity"
gene_type: "data/mcscanx/{genome}.gene_type"
clean_faa: "data/mcscanx/{species}.clean.faa"
blast_dmnd: "data/blast/{species}.dmnd"
query_clean: "data/mcscanx/{query}.clean.faa"
blast_db: "data/blast/{db}.dmnd"
output_diamond: "data/blast/{query}_vs_{db}.tsv"
target_vs_base: "data/blast/target_vs_base.tsv"
base_vs_target: "data/blast/base_vs_target.tsv"
combo_blast: "data/mcscanx/target_base.blast"
combo_collin: "data/mcscanx/target_base.collinearity"
all_pair: "data/mcscanx/all_pairs.tsv"