name: reactr
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - archspec=0.2.5
  - argcomplete=3.6.2
  - argh=0.31.3
  - bcbio-gff=0.7.1
  - bedtools=2.31.1
  - biopython=1.85
  - blast=2.16.0
  - boltons=24.0.0
  - brotli-python=1.1.0
  - bx-python=0.14.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - certifi=2025.11.12
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - colorama=0.4.6
  - conda=25.7.0
  - conda-libmamba-solver=25.3.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.11.0
  - cpp-expected=1.1.0
  - curl=8.13.0
  - diamond=2.1.12
  - distro=1.9.0
  - emboss=6.6.0
  - entrez-direct=22.4
  - fmt=11.1.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - frozendict=2.4.6
  - gffread=0.12.7
  - gffutils=0.13
  - gmap=2025.07.31
  - h2=4.2.0
  - hmmer
  - hpack=4.1.0
  - hyperframe=6.1.0
  - hyphy=2.5.73
  - icu=73
  - idna=3.10
  - importlib-metadata=8.7.0
  - iqtree=3.0.1
  - joblib=1.5.1
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - kakscalculator2=2.0.1
  - krb5=1.21.3
  - lerc=4.0.0
  - libarchive=3.7.7
  - libasprintf=0.25.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.13.0
  - libcxx=20.1.4 #not allowed linux, can eliminate it using sed
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgd=2.3.3
  - libgettextpo=0.25.1
  - libgfortran=5.0.0 #not allowed linux, can eliminate it using sed
  - libgfortran5=14.2.0 #not allowed linux, can eliminate it using sed
  - libharu=2.4.5
  - libiconv=1.18
  - libidn2=2.3.8
  - libintl=0.25.1 #not allowed linux, can eliminate it using sed
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmamba=2.1.1
  - libmambapy=2.1.1
  - libnghttp2=1.64.0
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libsolv=0.7.32
  - libsqlite=3.49.2
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libwebp-base=1.6.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.10.0
  - lzo=2.10
  - mamba=2.1.1
  - meme
  - menuinst=2.2.0
  - mpi=1.0
  - ncbi-datasets-cli=18.9.0
  - ncbi-vdb=3.2.1
  - ncurses=6.5
  - nlohmann_json=3.11.3
  - numpy=2.3.2
  - openmpi=4.1.6
  - openssl=3.6.0
  - packaging=25.0
  - pal2nal=14.1
  - paml=4.10.9
  - perl=5.32.1
  - perl-archive-tar=3.04
  - perl-carp=1.38
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.201
  - perl-compress-raw-zlib=2.202
  - perl-constant=1.33
  - perl-encode=3.21
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.70
  - perl-file-util=4.201720
  - perl-getopt-long=2.58
  - perl-io-compress=2.201
  - perl-io-zlib=1.15
  - perl-json=4.10
  - perl-json-xs=4.03
  - perl-lib=0.63
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-parent=0.236
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.70
  - perl-storable=3.15
  - perl-types-serialiser=1.01
  - pip=25.1.1
  - platformdirs=4.3.8
  - pluggy=1.5.0
  - primer3=2.6.1
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.22
  - pyfaidx=0.8.1.4
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.12.10
  - python_abi=3.12
  - pyvcf3=1.0.4
  - readline=8.2
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.3
  - rpsbproc=0.5.0
  - ruamel.yaml=0.18.10
  - ruamel.yaml.clib=0.2.8
  - scikit-learn=1.7.1
  - scipy=1.16.0
  - setuptools=80.1.0
  - simdjson=3.12.3
  - simplejson=3.20.1
  - six=1.17.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tqdm=4.67.1
  - truststore=0.10.1
  - urllib3=2.4.0
  - wget=1.21.4
  - wheel=0.45.1
  - yaml-cpp=0.8.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - openjdk=8
  - pip:
      - annotated-types==0.7.0
      - anthropic==0.37.1
      - anyio==4.12.0
      - bcbio-nextgen==1.1.5
      - blinker==1.9.0
      - click==8.2.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - dna-features-viewer==3.1.5
      - filelock==3.20.1
      - flask==3.1.1
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.2.3
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.12.0
      - kiwisolver==1.4.9
      - localizer==0.1.1
      - markupsafe==3.0.2
      - matplotlib==3.10.8
      - pandas==2.3.3
      - pillow==12.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygenomeviz==1.6.1
      - pytabix==0.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - run-cello==0.1.7
      - shellingham==1.5.4
      - sniffio==1.3.1
      - tokenizers==0.22.1
      - twobitreader==3.1.7
      - typer-slim==0.21.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - werkzeug==3.1.3
prefix: /Users/natlee/miniforge3
